### ISSUE TITLE
RSB Participants stuck on deactivation

### ISSUE THREAD

**Issue by DivineThreepwood** [open-rsx/rsb-java#28]
Release: rsb 0.18

In most cases the rsb participants can not be deactivated when calling the deactivation method of different participants simultaneously. After checking the stack trace it seems like a unlucky copy paste mistake in the SpreadReceiver.leave(...) method.

<pre>
            // join the group
            SpreadReceiver.this.spread.leave(group);

            // wait until the membership message confirms the join
            membershipHandler.waitForMessage();
</pre>

at least the comments are wrong because we are leaving the spread group and not joining it.
The thread blocks forever at the `waitForMessage()` method. Calling it after joining the group makes sense, but after leaving the group it's maybe not the best idea to wait for new incoming messages, right? Because the thread blocks the `subscriptions` lock at `rsb.transport.spread.SpreadMultiReceiver.unsubscribe(SpreadMultiReceiver.java:341)` all other participants calling the deactivation method blocks as well.

I would suggest to just remove the`membershipHandler.waitForMessage();`
call.

Stacktrace of the thread leaving the spread group:
<pre>
"ShutdownDaemon[UnitRemotePool]" #299 prio=5 os_prio=31 cpu=1.95ms elapsed=478.97s tid=0x00007ff8038e5800 nid=0xe5007 in Object.wait()  [0x000070002a4f9000]
   java.lang.Thread.State: WAITING (on object monitor)
	at java.lang.Object.wait(java.base@11.0.4/Native Method)
	- waiting on <no object reference available>
	at java.lang.Object.wait(java.base@11.0.4/Object.java:328)
	at rsb.transport.spread.SpreadReceiver$OneTimeWaitingMembershipHander.waitForMessage(SpreadReceiver.java:106)
	- waiting to re-lock in wait() <0x00000007896579f0> (a java.lang.Object)
	at rsb.transport.spread.SpreadReceiver$StateActive.leave(SpreadReceiver.java:322)
	at rsb.transport.spread.SpreadReceiver.leave(SpreadReceiver.java:415)
	at rsb.transport.spread.SpreadMultiReceiver.manageLeave(SpreadMultiReceiver.java:316)
	- locked <0x0000000782be5208> (a java.util.HashMap)
	at rsb.transport.spread.SpreadMultiReceiver.unsubscribe(SpreadMultiReceiver.java:360)
	- locked <0x0000000782be5208> (a java.util.HashMap)
	at rsb.transport.spread.MultiSpreadInPushConnector.deactivate(MultiSpreadInPushConnector.java:128)
	at rsb.eventprocessing.RouteConfiguratorUtility.deactivate(RouteConfiguratorUtility.java:119)
	- locked <0x0000000783b38f30> (a rsb.eventprocessing.RouteConfiguratorUtility)
	at rsb.eventprocessing.DefaultPushInRouteConfigurator.deactivate(DefaultPushInRouteConfigurator.java:79)
	- locked <0x0000000783b38f30> (a rsb.eventprocessing.RouteConfiguratorUtility)
	at rsb.Listener$StateActive.deactivate(Listener.java:97)
	at rsb.Listener.deactivate(Listener.java:196)
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedParticipant.deactivate(RSBSynchronizedParticipant.java:217)
</pre>

Example Stacktrace of all other participants:
<pre>
"pool-1-thread-1" #37 prio=5 os_prio=31 cpu=152.51ms elapsed=779.29s tid=0x00007ff7fc1f1000 nid=0x6703 waiting for monitor entry  [0x000070000f801000]
   java.lang.Thread.State: BLOCKED (on object monitor)
	at rsb.transport.spread.SpreadMultiReceiver.unsubscribe(SpreadMultiReceiver.java:341)
	- waiting to lock <0x0000000782be5208> (a java.util.HashMap)
	at rsb.transport.spread.MultiSpreadInPushConnector.deactivate(MultiSpreadInPushConnector.java:128)
	at rsb.eventprocessing.RouteConfiguratorUtility.deactivate(RouteConfiguratorUtility.java:119)
	- locked <0x0000000783c36438> (a rsb.eventprocessing.RouteConfiguratorUtility)
	at rsb.eventprocessing.DefaultPushInRouteConfigurator.deactivate(DefaultPushInRouteConfigurator.java:79)
	- locked <0x0000000783c36438> (a rsb.eventprocessing.RouteConfiguratorUtility)
	at rsb.Listener$StateActive.deactivate(Listener.java:97)
	at rsb.Listener.deactivate(Listener.java:196)
	at rsb.patterns.Method$StateActive.deactivate(Method.java:83)
	at rsb.patterns.Method.deactivate(Method.java:207)
	at rsb.patterns.Server$StateActive.deactivate(Server.java:77)
	at rsb.patterns.Server.deactivate(Server.java:225)
	- locked <0x0000000783c33858> (a rsb.patterns.LocalServer)
	at org.openbase.jul.extension.rsb.com.RSBSynchronizedParticipant.lambda$deactivate$0(RSBSynchronizedParticipant.java:205)
</pre>

**Comment by scymtym** [comment]
Thank you for the report.

First of all, could you provide a self-contained test program that allows reproducing the issue? Otherwise we have no way of making sure we understand and fix the problem properly. Furthermore, log messages for the `rsb.transport.spread` package at level `FINEST` could help.

> at least the comments are wrong because we are leaving the spread group and not joining it.

Of course.

> The thread blocks forever at the `waitForMessage()` method. Calling it after joining the group makes sense, but after leaving the group it's maybe not the best idea to wait for new incoming messages, right?

If `waitForMessage` never returns, something is wrong since Spread is definitely supposed to send a membership notification for leaving the group. I wouldn't say waiting for the leave operation to complete doesn't make sense. Otherwise, for example, we wouldn't know at which point we definitely no longer receive messages for the group in question.

> Because the thread blocks the `subscriptions` lock [...]

That in itself is not a problem since the leave operation must finish in a finite (short) amount of time.

I could imagine something like the Spread message queue being full or maybe a deadlock caused by calling `deactivate()` from an unexpected place, but again, a self-contained test program or log messages may shed light onto the issue.

**Comment by DivineThreepwood** [comment]
Thanks for your fast response.

> First of all, could you provide a self-contained test program that allows reproducing the issue? Otherwise we have no way of making sure we understand and fix the problem properly.

I just added an example code blob to the main issue description.

> Furthermore, log messages for the rsb.transport.spread package at level FINEST could help.

I switched the log level to "ALL" but got no additional log messages, any idea?

> If waitForMessage never returns, something is wrong since Spread is definitely supposed to send a membership notification for leaving the group. 

That's good to know.

**Comment by DivineThreepwood** [comment]
Could you reproduce the issue by using the offered code snipped? 
Otherwise, please let me know if I can further support you to solve this issue.
